### ISSUE TITLE
Failed to run simple rust plugin in playground

### ISSUE THREAD

**Issue by piaoger** [extism/extism#183]
Following error was found while trying to run a pluin following the tutorial "write a plugin in rust".  I also tried to upload code.wasm shipped with source code and it works fine instead.

![image](https://user-images.githubusercontent.com/179429/209436475-513988e3-e147-4219-9dbe-97f0397318c8.png)

- env
  rustc 1.66.0 (69f9c33d7 2022-12-12)

- my cargo.toml: 

```toml
[lib]
crate_type = ["cdylib"]

[dependencies]
extism-pdk = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
```
[wasm_web_plugin.zip](https://github.com/extism/extism/files/10298573/wasm_web_plugin.zip)
